### PR TITLE
Generate WIT file from Rust module

### PR DESCRIPTION
**Pull request by sviezypan**
This PR introduces capability of a rust macro to generate WIT file from annotated rust module. Some examples are in examples project and readme.

### CODE REVIEW

**Comment by vigoo** [comment]
I think you could just check if the target WIT's contents are the same, and not write to the file if so. That way although the macro would always run, it would not change the file times and make the WIT files dirty.

**Comment by vigoo** [comment]
I'm doing this in zio-k8s/zio-aws code generators, I think :)

**Comment by vigoo** [comment]
And for publishing, you can just copy the cargo settings and CI from for example https://github.com/golemcloud/golem-wasm-ast - there is an org secret that applies to this repo too for crates.io

**Comment by sviezypan** [comment]
> I think you could just check if the target WIT's contents are the same, and not write to the file if so. That way although the macro would always run, it would not change the file times and make the WIT files dirty.

So you mean that macro would also read the file and compare the content with whatever it was trying to write and do not rewrite in case the content is the same?

**Comment by vigoo** [comment]
Yes that's what I suggest

**Review by adamgfraser — APPROVED** [review]

**Pull request merged**
